### ISSUE TITLE
submitLogLevel := Level.Debug not displaying full command

### ISSUE THREAD

**Issue by cdelgadob** [crakjie/sbt-spark-plugin#3]
If I add these lines to the build.sbt file, it doesn't show the command line being launched

```
import sbt._

submitLogLevel := Level.Debug
```

**Comment by crakjie** [comment]
submitLogLevel write debug into the sbt debug output. try 

```
import sbt._

submitLogLevel := Level.Debug
logLevel := Level.Debug //which is the sbt log level
```

Maybe it's could write it in another output, to not have to see all debug output of spark.

**Comment by cdelgadob** [comment]
Solved :)
